# Generated by Django 6.0.7 on 2026-09-22 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CantactInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcademyAddress', models.CharField(max_length=200)),
                ('phone_Number', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('OpeningHours', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=200)),
                ('days', models.CharField(max_length=300)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField()),
                ('fee', models.CharField(max_length=300)),
                ('CourseTeacher', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('level', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WhychooseUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=200)),
                ('DateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('PrevSchool', models.CharField(max_length=200)),
                ('PrevClass', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Parent_Guardian_Name', models.CharField(max_length=200)),
                ('Relation_with_student', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Registeration_Date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending')),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academyproject.classes')),
                ('Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academyproject.course')),
            ],
        ),
        migrations.CreateModel(
            name='registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200, null=True)),
                ('DateofBirth', models.DateField()),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('ParentphoneNum', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('parentOrGuardianName', models.CharField(max_length=200)),
                ('AdsmissionDate', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='studentPro/')),
                ('studentUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('DateOfBirth', models.DateField()),
                ('PrevSchool', models.CharField(max_length=200)),
                ('PrevClass', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Parent_Guardian_Name', models.CharField(max_length=200)),
                ('Relation_with_student', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Registeration_Date', models.DateField(auto_now_add=True)),
                ('classs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academyproject.classes')),
                ('course', models.ManyToManyField(blank=True, to='academyproject.course')),
                ('subjects', models.ManyToManyField(blank=True, to='academyproject.subjectsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('joining_date', models.DateField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='teacher_prof/')),
                ('status', models.CharField(max_length=200)),
                ('TeacherUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subjectsmodel',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academyproject.teacheracc'),
        ),
        migrations.AddField(
            model_name='classes',
            name='Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academyproject.teacheracc'),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPresent', models.CharField(max_length=200)),
                ('courseOrClass', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academyproject.studentacc')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academyproject.teacheracc')),
            ],
        ),
    ]
